#!/bin/bash
set -euxo pipefail

echo "Checking if the folder instruqt exists."

if [ -d /root/instruqttest ]
then
    echo "The folder instruqttest exists"
else
    fail-message "There is no folder named instruqttest, did you create it?"
fi